version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SPOTIFY_CLIENT: ${SPOTIFY_CLIENT}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  db_data:
